### ISSUE TITLE
Open Street Map no longer avaiable

### ISSUE THREAD

**Issue by noesting** [aldeed/meteor-geocoder#16]
Hello,

I am trying to get latitude and longitude from some address strings using this geocoder and Open Street Map as provider.  
This is my code:
```typescript
    const geocoder = new GeoCoder({
        geocoderProvider: "openstreetmap",
    })

    try {
        const result = geocoder.geocode(location);

        // catch empty response case
        if (!result || result.length === 0) {
            console.log('error, response does not exist');
            throw new Meteor.Error('Geo-Error', 'There is no result for the given geo coordinates.', location);
        }

        return result[0];
    } catch (error) {
        console.log('error', error);
        throw new Meteor.Error('Geo-Error', error);
    }
```

This code used to work fine, but it seems OSM has moved some of their services so I get this Error message:
```
I20180731-08:58:02.811(2)? error Error: Response status code is 301
I20180731-08:58:02.813(2)?     at IncomingMessage.<anonymous> (/home/noesting/.meteor/packages/aldeed_geocoder/.0.3.8.7i23iv++os+web.browser+web.cordova/npm/node_modules/node-geocoder/lib/httpadapter/httpadapter.js:59:25)
I20180731-08:58:02.814(2)?     at emitNone (events.js:111:20)
I20180731-08:58:02.815(2)?     at IncomingMessage.emit (events.js:208:7)
I20180731-08:58:02.815(2)?     at endReadableNT (_stream_readable.js:1064:12)
I20180731-08:58:02.815(2)?     at _combinedTickCallback (internal/process/next_tick.js:138:11)
I20180731-08:58:02.816(2)?     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Ist this a problem with this package or can I adjust things by myself to get it working again?

Thanks everyone

**Comment by aldeed** [comment]
This package just adds fibers support to [node-geocoder](https://www.npmjs.com/package/node-geocoder). I'd suggest switching to use the NPM package directly unless you're using a really old version of Meteor. Using the latest version of the NPM package might fix your issue.

**Comment by noesting** [comment]
Using node-geocoder directly works. Thank you @aldeed
