### ISSUE TITLE
Invalid address geocoding hangs server up

### ISSUE THREAD

**Issue by epaminond** [aldeed/meteor-geocoder#3]
I have a simple meteor method:

``` javascript
geoCode: function(address) {
  check(address, String);
  var geo = new GeoCoder();
  var result = geo.geocode(address);
  return result;
}
```

Server returns `error: 500, reason: "Internal server error"` and doesn't respond to any further requests if I call it with invalid address like this:

``` javascript
Meteor.call('geoCode', 'shjhjfd sdfs dssdf', function(err, res) {console.log(err, res)})
```

On the server side following error is reported:

``` javascript
I20141206-10:38:33.384(2)? Exception while invoking method 'geoCode' Error: Status is ZERO_RESULTS.
I20141206-10:38:33.385(2)?     at Object.Future.wait (/home/epaminond/.meteor/packages/meteor-tool/.1.0.35.ftql1v++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:326:15)
I20141206-10:38:33.386(2)?     at packages/meteor/helpers.js:118
I20141206-10:38:33.387(2)?     at geoCoderConstructor.geoCoderGeocode [as geocode] (packages/aldeed:geocoder/geocoder.js:26)
I20141206-10:38:33.387(2)?     at Meteor.methods.geoCode (server/server/server/methods.next.js:14:19)
I20141206-10:38:33.387(2)?     at Object.methods.rateLimit.callFunctionsInQueue (packages/matteodem:easy-security/lib/easy-security.js:72)
I20141206-10:38:33.388(2)?     at null.<anonymous> (packages/matteodem:easy-security/lib/easy-security.js:113)
I20141206-10:38:33.388(2)?     at null.<anonymous> (packages/matteodem:easy-security/lib/easy-security.js:54)
I20141206-10:38:33.389(2)?     at packages/check/match.js:105
I20141206-10:38:33.389(2)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20141206-10:38:33.390(2)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:104)
I20141206-10:38:33.391(2)?     - - - - -
I20141206-10:38:33.391(2)?     at /home/epaminond/.meteor/packages/aldeed:geocoder/.0.3.3.xguy3a++os+web.browser+web.cordova/npm/node_modules/node-geocoder/lib/geocoder/googlegeocoder.js:62:33
I20141206-10:38:33.392(2)?     at IncomingMessage.<anonymous> (/home/epaminond/.meteor/packages/aldeed:geocoder/.0.3.3.xguy3a++os+web.browser+web.cordova/npm/node_modules/node-geocoder/lib/httpadapter/httpadapter.js:42:17)
I20141206-10:38:33.392(2)?     at IncomingMessage.emit (events.js:117:20)
I20141206-10:38:33.392(2)?     at _stream_readable.js:929:16
I20141206-10:38:33.393(2)?     at process._tickCallback (node.js:419:13)
```

I use `aldeed:geocoder@0.3.3` and `METEOR@1.0`.

**Comment by ouya99** [comment]
I am also having this issue using Meteor@1.2.1 and aldeed:geocoder@0.3.8

Has this been fixed?
